import { Preset, HandleSides } from "@/lib/types";

export const PRESETS: Preset[] = [
  {
    name: "Small Tray",
    width: 80,
    height: 30,
    length: 120,
    wallThickness: 2,
    cornerRadius: 0,
    pattern: "none",
    handles: false,
  },
  {
    name: "Storage Bin",
    width: 150,
    height: 100,
    length: 200,
    wallThickness: 3,
    cornerRadius: 0,
    pattern: "none",
    handles: true,
    handleSides: "front-back",
    handleWidth: 80,
    handleHeight: 25,
    handleTopOffset: 10,
  },
  {
    name: "Pencil Cup",
    width: 80,
    height: 100,
    length: 80,
    wallThickness: 2,
    cornerRadius: 15,
    pattern: "hexagons",
    patternSize: 6,
    patternSpacing: 2,
    handles: false,
  },
  {
    name: "Fruit Basket",
    width: 200,
    height: 80,
    length: 250,
    wallThickness: 2.5,
    cornerRadius: 20,
    pattern: "holes",
    patternSize: 8,
    patternSpacing: 4,
    handles: true,
    handleSides: "front-back",
    handleWidth: 70,
    handleHeight: 20,
    handleTopOffset: 8,
  },
  {
    name: "Desk Organizer",
    width: 100,
    height: 50,
    length: 180,
    wallThickness: 2,
    cornerRadius: 8,
    pattern: "none",
    handles: false,
  },
  {
    name: "Laundry Hamper",
    width: 250,
    height: 180,
    length: 250,
    wallThickness: 3,
    cornerRadius: 30,
    pattern: "holes",
    patternSize: 10,
    patternSpacing: 5,
    handles: true,
    handleSides: "all",
    handleWidth: 80,
    handleHeight: 30,
    handleTopOffset: 15,
  },
  {
    name: "Soap Dish",
    width: 60,
    height: 15,
    length: 90,
    wallThickness: 1.5,
    cornerRadius: 12,
    pattern: "none",
    handles: false,
  },
  {
    name: "Tool Caddy",
    width: 120,
    height: 90,
    length: 180,
    wallThickness: 3,
    cornerRadius: 5,
    pattern: "hexagons",
    patternSize: 8,
    patternSpacing: 3,
    handles: true,
    handleSides: "left-right",
    handleWidth: 60,
    handleHeight: 25,
    handleTopOffset: 10,
  },
  {
    name: "Planter",
    width: 110,
    height: 85,
    length: 110,
    wallThickness: 2.5,
    cornerRadius: 18,
    pattern: "holes",
    patternSize: 6,
    patternSpacing: 3,
    handles: false,
  },
  {
    name: "Drawer Insert",
    width: 160,
    height: 40,
    length: 220,
    wallThickness: 2,
    cornerRadius: 4,
    pattern: "none",
    handles: false,
  },
  {
    name: "Kitchen Drying Basket",
    width: 180,
    height: 70,
    length: 240,
    wallThickness: 2,
    cornerRadius: 12,
    pattern: "holes",
    patternSize: 6,
    patternSpacing: 3,
    handles: true,
    handleSides: "front-back",
    handleWidth: 70,
    handleHeight: 20,
    handleTopOffset: 10,
  },
  {
    name: "Grid Organizer Bin",
    width: 180,
    height: 100,
    length: 180,
    wallThickness: 2.5,
    cornerRadius: 6,
    pattern: "hexagons",
    patternSize: 8,
    patternSpacing: 3,
    handles: false,
  },
  {
    name: "Spice Rack Bin",
    width: 60,
    height: 80,
    length: 200,
    wallThickness: 2,
    cornerRadius: 8,
    pattern: "none",
    handles: false,
  },
];

export const HANDLE_SIDE_OPTIONS: { value: HandleSides; label: string }[] = [
  { value: "front-back", label: "Front & Back" },
  { value: "left-right", label: "Left & Right" },
  { value: "all", label: "All Sides" },
];

export const PALETTE = [
  "#b8b8b8",
  "#e8e8e8",
  "#4a4a4a",
  "#1a1a1a",
  "#ef4444",
  "#f97316",
  "#eab308",
  "#22c55e",
  "#06b6d4",
  "#3b82f6",
  "#8b5cf6",
  "#ec4899",
  "#92400e",
  "#365314",
  "#1e3a5f",
  "#581c87",
];

export const DEFAULT_BASKET_COLOR = PALETTE[0];
